version: "3"
services:
  nginx:
    image: "lucasgmm20/portilex-proxy"
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/my-site.com.crt:/etc/nginx/my-site.com.crt # certificate
      - ./nginx/my-site.com.key:/etc/nginx/my-site.com.key # key
    ports:
      - "3000:443"
  mongo:
    image: mongo:4.4.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - "27017"
  server:
    image: lucasgmm20/portilex-server-dev
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    expose:
      - "5000"
  client:
    image: lucasgmm20/portilex-client-dev
    build:
      dockerfile: Dockerfile.dev
      context: "./client"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    expose:
      - "8080"