version: "3"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - "27017"
  server:
    image: lucasgmm20/portilex-server-dev
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    expose:
      - "5000"
  
